### PR TITLE
fix(switch): making sure toggle isn't called when switch is disabled

### LINKED ISSUE #2215: [bug] switch: disabled switches are still clickable in Firefox
## Steps to reproduce
- Go to https://patternflyelements.org/components/switch/demo/#disabled in Firefox
- Click on the disabled switch
- Notice how the switch is still clickable and changing from on to off

### PR DESCRIPTION
**Pull request by kylebuch8**
Fixes issue in Firefox where when `pfe-switch` is disabled, the switch can still be toggled. This PR exits the `#toggle` method if `pfe-switch` is disabled.

Fixes #2215.

### Related issues
- #2215

### Preview
- Go to https://deploy-preview-2221--patternfly-elements.netlify.app/components/switch/demo/#disabled in Firefox
- Try to click on the switch to make it toggle

### CODE REVIEW

File: elements/pfe-switch/BaseSwitch.ts [hunk 1]
```diff
@@ -84,6 +84,10 @@ export abstract class BaseSwitch extends LitElement {
   }
 
   #toggle() {
+    if (this.disabled) {
```
Comment (bennypowers) [inline elements/pfe-switch/BaseSwitch.ts:87]: this is woke
but bespoke? put `pointer-events: none` on the disabled host. use

```css
:host([disabled]),
:host(:disabled) {
  pointer-events: none;
}
```

**Review by bennypowers — CHANGES_REQUESTED** [review]

File: elements/pfe-switch/BaseSwitch.ts (hunk 1 above)
Comment (kylebuch8) [reply elements/pfe-switch/BaseSwitch.ts:87]: Are you suggesting that I remove the early return in favor of the CSS change? Or are you suggesting that I add this too?

Comment (bennypowers) [reply elements/pfe-switch/BaseSwitch.ts:87]: i think the css would do the trick on it's own, but i don't object to the early return

Comment (bennypowers) [reply elements/pfe-switch/BaseSwitch.ts:87]: make sure to put it in base styles since it's not pfe-specific

**Review by bennypowers — APPROVED** [review]
Lonely geezers trade magazines (don't call hr on me)
