### PR TITLE
fix(popover): prevent scrollbar

### LINKED ISSUE #2648: [Bug]pf-popover - Responsiveness issue
### Impacted component(s)

- pf-popover and all the other components that have pf-popover implemented.

### Steps to reproduce

The pf-popover implementation maintains the popover element in the DOM even when it is not visible or active. This persistent presence in the DOM causes unintended visual effects, including spacing inconsistencies and horizontal scroll issues, particularly when the popover is positioned at the far right edge of the page.

### Expected behaviour

The popover should not be taking any space when its not opened

### Screenshots

Please refer to the screenshots given below.
In the cp-date-picker, pf-popover is used for dialog and its seen that the popover is taking space and creating horizontal scroll when its the rightmost element and in mobile resolutions

Screenshot 2023-11-09 at 4 12 53 PM

Screenshot 2023-11-09 at 4 13 18 PM

## Related issues

- #100

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. hide the dialog before the popover animates open and after it animates closed
2. Add a demo to illustrate the solution

## Testing Instructions

1. https://deploy-preview-2730--patternfly-elements.netlify.app/components/popover/demo/edge-of-viewport/ and set the viewport width so that the popover is at the far edge. For me, that was 1190 pixels wide.
2. Observe that there is not horizontal scrollbar
3. confirm that opening and closing the popover in various ways works as expected
4. repeat step 3 for the other demo files

## Notes to Reviewers

1. Closes #2648

### CODE REVIEW

**Comment by Arathy-s** [comment]
Tested locally as mentioned in the testing instructions.
The horizontal scroll bar issue is now resolved.

File: elements/pf-popover/pf-popover.ts [hunk 1]
```diff
@@ -395,6 +399,10 @@ export class PfPopover extends LitElement {
     `;
   }
 
+  updated() {
+    // this.#hideDialog = !this.#float.open;
+  }
+
```
Comment (bennypowers) [inline elements/pf-popover/pf-popover.ts:405]:
```suggestion
```
removed unused callback

**Review by Arathy-s — APPROVED** [review]
The changes looks good to me.
The horizontal scrollbar issue resolved.
