### PR TITLE
fix(switch): only showing check if show-check-icon is true

### LINKED ISSUE #2207: switch: check is always showing
image

The check should only show when the `show-check-icon` attribute is present.

### PR DESCRIPTION
**Pull request by kylebuch8**
Fixes #2207 

Preview url: https://deploy-preview-2208--patternfly-elements.netlify.app/components/switch/

### CODE REVIEW

File: elements/pfe-switch/BaseSwitch.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export abstract class BaseSwitch extends LitElement {
     return html`
       <div id="container" tabindex="0">
         <svg id="toggle" fill="currentColor" height="1em" width="1em" viewBox="0 0 512 512">
-            <path d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"/>
+          <path d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z" ?hidden=${!this.showCheckIcon}/>
```
Comment (bennypowers) [inline elements/pfe-switch/BaseSwitch.ts:50]: Probably better to put hidden before d, for readability

**Review by bennypowers — APPROVED** [review]

**Review by zeroedin — APPROVED** [review]
let good times manifest
