### PR TITLE
fix: cascading the "on" attribute on pfe-content-set

### LINKED ISSUE #720: pfe-content-set does not cascade the on="dark" attribute
image

As such, text that is inside the content set is the wrong color:
image

### PR DESCRIPTION
**Pull request by kylebuch8**
Fixes #720

### Testing instructions
Be sure to include detailed instructions on how your update can be tested by another developer.

1. View the "Using pfe-color to control the theme" section of the demo.
2. Verify that the "on" attribute has been added to both the tabs and the accordion.
3. Verify that the newly added tests for pfe-content-set are passing

### CODE REVIEW

**Comment by kylebuch8** [comment]
@castastrophe Great suggestion! That simplified things a bunch. I've updated the PR with your recommendation.

File: elements/pfe-accordion/src/pfe-accordion.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ class PfeAccordion extends PFElement {
   }
 
   static get observedAttributes() {
-    return ["pfe-disclosure"]
+    return ["pfe-disclosure", "on"]
```
Comment (castastrophe) [inline elements/pfe-accordion/src/pfe-accordion.js]: Is this still needed after the latest updates?

Comment (kylebuch8) [reply elements/pfe-accordion/src/pfe-accordion.js]: I fixed that too. It's not needed anymore.
