### PR TITLE
fix(icon)!: remove BaseIcon

### LINKED ISSUE #2621: Remove BaseIcon

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #2621

## What I did

1. remove baseicon

## Testing Instructions

1. dp demo vs prod

## Notes to Reviewers

1. don't merge until non-breaking prs are merged and 2.5.0 is released
2. take special care to review JSDoc: slot, csspart, cssprop

### CODE REVIEW

File: elements/pf-icon/pf-icon.ts [hunk 1]
```diff
@@ -12,15 +31,138 @@ import style from './pf-icon.css';
...
  */
 @customElement('pf-icon')
-export class PfIcon extends BaseIcon {
-  public static readonly styles = [...BaseIcon.styles, style];
+export class PfIcon extends LitElement {
+  public static readonly styles = [style];
 
   public static defaultIconSet = 'fas';
 
+  public static addIconSet(setName: string, getter: URLGetter) {
```
Comment (zeroedin) [inline elements/pf-icon/pf-icon.ts:42]:
```Suggestion
  /**
   * Register a new icon set
   * @param setName - The name of the icon set
   * @param getter - A function that returns the URL of an icon
   * example: 
   *
   * PfIcon.addIconSet('rh', (set, icon) =>
   *   new URL(`./icons/${set}/${icon}.js`, import.meta.url));
   * 
   */
  public static addIconSet(setName: string, getter: URLGetter) {
  ```

File: elements/pf-icon/pf-icon.ts [hunk 2]
```diff
@@ -12,15 +31,138 @@ import style from './pf-icon.css';
...
+      Logger.warn(`[${this.name}.addIconSet(setName, getter)]: getter must be a function`);
+    } else {
+      this.getters.set(setName, getter);
+      for (const instance of this.instances) {
+        instance.load();
+      }
+    }
+  }
+
+  public static getIconUrl: URLGetter = (set: string, icon: string) =>
```
Comment (zeroedin) [inline elements/pf-icon/pf-icon.ts:53]:
```Suggestion
  /**
   * Remove an icon set
   * @param set - The name of the icon set
   * @param icon - The name of the icon
   * @returns The URL of the icon
   */
  public static getIconUrl: URLGetter = (set: string, icon: string) =>
```

File: .changeset/remove-base-icon.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+---
```
Comment (zeroedin) [inline .changeset/remove-base-icon.md:1]:
```Suggestion
--- 
```
Ignore suggestion, blocking comment for approval.

**Don't merge until non-breaking changes are released in 2.5.0**

**Review by zeroedin — APPROVED** [review]
LGTM
